name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Azure DevOps remote safely
        run: |
          git remote get-url azure || git remote add azure "https://${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/IICLDEV/Idental/_git/Idental-UI"

      - name: Force push to Azure DevOps
        run: |
          git push azure --force --all
          git push azure --force --tags
